In [ ]:
CREATE TABLE Customers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customername VARCHAR(80) UNIQUE NOT NULL,
    password VARCHAR(200) NOT NULL,
    is_admin BOOLEAN
);

CREATE TABLE users (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    users VARCHAR(100) NOT NULL
);

create TABLE publishers (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    publisher VARCHAR(100) NOT NULL
);

CREATE TABLE genre (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    genre VARCHAR(100) NOT NULL
);

CREATE TABLE keywords (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    keyword VARCHAR(100) NOT NULL,
    genre_id INT UNSIGNED,
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE novels (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    users_id INT UNSIGNED,
    publisher_id INT UNSIGNED,
    price SMALLINT UNSIGNED,
    ing VARCHAR(50),
    author VARCHAR(100),
    genre_id INT UNSIGNED,
    viewCount BIGINT UNSIGNED,
    reviewCount BIGINT UNSIGNED,
    score FLOAT,
    uploaded INT UNSIGNED,
    date DATE,
    free_info TINYINT UNSIGNED,
    keywords JSON,
    FOREIGN KEY (users_id) REFERENCES users(id),
    FOREIGN KEY (publisher_id) REFERENCES publishers(id),
    FOREIGN KEY (genre_id) REFERENCES genre(id)
);

CREATE TABLE images (
  id int unsigned NOT NULL AUTO_INCREMENT,
  src varchar(255) NOT NULL,
  novel_id int unsigned DEFAULT NULL UNIQUE,
  PRIMARY KEY (id),
  CONSTRAINT images_ibfk_1 FOREIGN KEY (novel_id) REFERENCES novels (id)
);

INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=AQJvj/hAHIk7IXFd/AMRhBKLDvZD4FrAIeFOglk&filename=o1/dims/resize/384', 11972);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=bFdV4z/hAFsBYDaq2/9KazqmMK81JpKxps7O8zeK&filename=o1/dims/resize/384', 10050);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=b6pOTE/hzMUatdJ87/GE6TEOPDjbhEmAFjXlDpsK&filename=o1/dims/resize/384', 13413);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=bpiDit/hzCs9DWNT1/jMhpkicaYobRQHVxO6muvk&filename=o1/dims/resize/384', 15054);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=ccRsk8/hzhOnijUmq/AMkGwPwKYkcx0kwD9PWHKk&filename=o1/dims/resize/384', 16028);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=42Iyd/hycujy0sO3/9b8X9owJAorriycw5D98KK&filename=o1/dims/resize/384', 16426);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=7NTEx/hydtBd8kyv/NzsIsSNvZyLbTKF93VBxkk&filename=o1/dims/resize/384', 16462);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=GNoTJ/hycurjg87T/AhyVjfqenuVLVRRLxroRF1&filename=o1/dims/resize/384', 16480);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=cWP4v9/hybnBAQ3kB/USCRrRzFp8q0iL3UXykZ40&filename=o1/dims/resize/384', 16582);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=brbNfW/hya4pHjRwn/pLKBpYkgtsQUszPUdjcweK&filename=o1/dims/resize/384', 16608);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=jEM7w/hyEdfwQjoS/16tNvL0hhJ0obytrLeNBIk&filename=o1/dims/resize/384', 18751);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=bTfeKA/hyzcFmjsMY/Y6fpED2qNGrlvJUlckiKr0&filename=o1/dims/resize/384', 19286);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=dzDwD/hywgIsv3LN/Uhkk99L7rexdBKh3JywrO0&filename=o1/dims/resize/384', 19528);
INSERT INTO images (src, novel_id) VALUES ('https://page-images.kakaoentcdn.com/download/resource?kid=c9Uko/hyjanIszIw/cRl6ZWHnDcSmqfpT8Us9qK&filename=o1/dims/resize/384', 19968);

commit;

In [ ]:
# publisers 테이블에 넣을 값 생성 코드

# 'publisher' 열의 고유 값 추출
unique_publishers = data['publisher'].unique()

# INSERT 문 생성
insert_statements = []
for publisher in unique_publishers:
    insert_statements.append(f"INSERT INTO publishers (publisher) VALUES ('{publisher}');")

# 결과 출력
for statement in insert_statements:
    print(statement)

# + 누락 데이터
insert into publishers (publisher) values('삼양씨앤씨');
INSERT INTO team1.novels
(title, users_id, publisher_id, price, ing, author, genre_id, viewCount, reviewCount, score, uploaded, `date`, free_info, keywords)
VALUES('두 번 사는 랭커', 1, 270, 100, '완결', '사도연', 1, 330000000, 146000, 9.9, 862, '17-10-16', 0, '["차원이동","복수","생존","탑등반","영웅/신화","노력","성장","포식/흡수"]');

In [ ]:
# keywords 테이블에 넣을 데이터 생성 코드

# Load the CSV file
file_path = 'Data.csv'
data = pd.read_csv(file_path)

# Extract unique keywords
keywords_set = set()
for keywords in data['keywords']:
    if pd.notna(keywords):
        keywords_list = keywords.split('#')
        keywords_set.update([kw.strip() for kw in keywords_list if kw.strip()])

unique_keywords = list(keywords_set)

sql_insert_keywords = "INSERT INTO keywords (keyword) VALUES "
values = ", ".join([f"('{kw}')" for kw in unique_keywords])
sql_insert_keywords += values + ";"

print(sql_insert_keywords)

In [ ]:
# novels 테이블

import pandas as pd
from sqlalchemy import create_engine, MetaData, Table
from sqlalchemy.orm import sessionmaker

# 데이터베이스 연결 설정
db_uri = 'mysql+pymysql://root:mysql@localhost/team1'  # 이 부분을 실제 사용자 이름과 비밀번호로 수정해야 합니다.
engine = create_engine(db_uri)
Session = sessionmaker(bind=engine)
session = Session()

# 기존 데이터 불러오기
data = pd.read_csv('Data.csv')

# 장르별로 키워드를 #으로 분할
grouped = data.groupby('genre')['keywords'].apply(lambda x: '#'.join(x)).reset_index()
grouped['keywords'] = grouped['keywords'].apply(lambda x: [kw for kw in set(x.split('#')) if kw])

# 장르 테이블 데이터 수동 정의
genre_dict = {
    '판타지': 1,
    '로판': 2,
    '현판': 3,
    '로맨스': 4,
    'BL': 5,
    '무협': 6,
    '드라마': 7
}

# 메타데이터 리플렉션
metadata = MetaData()
metadata.reflect(bind=engine)

keywords_table = metadata.tables['keywords']

insert_data = []

# 키워드 데이터 준비 및 삽입
for _, row in grouped.iterrows():
    genre = row['genre']
    if genre in genre_dict:
        genre_id = genre_dict[genre]
        keywords = row['keywords']
        for keyword in keywords:
            insert_data.append({'keyword': keyword, 'genre_id': genre_id})

# 키워드 데이터베이스에 삽입 및 커밋
with engine.begin() as connection:  # `begin` 사용하여 자동으로 커밋 또는 롤백 처리
    connection.execute(keywords_table.insert(), insert_data)

In [ ]:
# images 테이블에 값 넣는 코드

import pandas as pd
from sqlalchemy import create_engine, text

# CSV 파일 경로
novel_images_csv_path = 'novel_images.csv'

# CSV 파일 읽기
novel_images_df = pd.read_csv(novel_images_csv_path)

# DB 연결 설정 (MySQL 예시, 적절한 DB URL로 교체)
DATABASE_URL = "mysql+mysqlconnector://root:mysql@localhost/team1"
engine = create_engine(DATABASE_URL)

# images 테이블의 모든 데이터 삭제 및 새로운 데이터 삽입
with engine.connect() as connection:
    # 트랜잭션 시작
    trans = connection.begin()
    try:
        # images 테이블의 모든 데이터 삭제
        connection.execute(text("DELETE FROM images"))
        print("Images 테이블의 모든 데이터 삭제 완료")

        # 새로운 데이터 삽입
        for _, row in novel_images_df.iterrows():
            connection.execute(
                text("""
                INSERT INTO images (src, novel_id)
                VALUES (:src, :novel_id)
                """),
                {'src': row['src'], 'novel_id': row['novel_id']}
            )
            print(f"Inserted src={row['src']} with novel_id={row['novel_id']} into images table")

        # 트랜잭션 커밋
        trans.commit()
        print("트랜잭션 커밋 완료")
    except Exception as e:
        # 예외 발생 시 롤백
        trans.rollback()
        print(f"트랜잭션 롤백 발생: {e}")

print("Images 테이블에 데이터 삭제 및 새 데이터 삽입 완료")